######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 24 03:25:06 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
